server:
  port: 9010

spring:
  application:
    name: gateway
  #############################新增网关配置###########################
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
#        - id: weatherpush_receiver #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:9001          #匹配后提供服务的路由地址
#          #uri: lb://cloud-payment-com.li.springcloud.service #匹配后提供服务的路由地址
#          predicates:
#            - Path=/admin/receiver/**         # 断言，路径相匹配的进行路由
#
#        - id: weatherpush_weatherpush #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:9001          #匹配后提供服务的路由地址
#            #uri: lb://cloud-payment-com.li.springcloud.service #匹配后提供服务的路由地址
#          predicates:
#            - Path=/admin/weatherpush/**         # 断言，路径相匹配的进行路由

        - id: blog #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8080          #匹配后提供服务的路由地址
          #uri: lb://cloud-payment-com.li.springcloud.service #匹配后提供服务的路由地址
          predicates:
            - Path=/admin/*/**         # 断言，路径相匹配的进行路由

        - id: blog2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8080          #匹配后提供服务的路由地址
            #uri: lb://cloud-payment-com.li.springcloud.service #匹配后提供服务的路由地址
          predicates:
            - Path=/*         # 断言，路径相匹配的进行路由
####################################################################


eureka:
  instance:
    hostname:  gateway #cloud-gateway-com.li.springcloud.service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka
